### ISSUE TITLE
SDL 1.2 headers included <stddef.h> but sdl12-compat no longer does

### ISSUE THREAD

**Issue by smcv** [libsdl-org/sdl12-compat#297]
I've been trying to rebuild various Debian packages against sdl12-compat headers, which is likely to be a prerequisite for Debian switching to sdl12-compat.

One game, [berusky](https://tracker.debian.org/pkg/berusky), compiles OK with classic SDL 1.2, but failed to compile with sdl12-compat headers:

```
In file included from stack.h:31,
                 from level_game.h:32,
                 from berusky.h:131:
level_game.cpp: In constructor 'level_generic::level_generic(ITEM_REPOSITORY*)':
level_game.cpp:107:29: error: expected primary-expression before ',' token
  107 |   assert(offsetof(LEVEL_DISK, signum) == 0);
      |                             ^
level_game.cpp:107:31: error: 'signum' was not declared in this scope; did you mean 'signed'?
  107 |   assert(offsetof(LEVEL_DISK, signum) == 0);
      |                               ^~~~~~
level_game.cpp:107:10: error: 'offsetof' was not declared in this scope
  107 |   assert(offsetof(LEVEL_DISK, signum) == 0);
      |          ^~~~~~~~
level_game.cpp:35:1: note: 'offsetof' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
   34 | #include "berusky.h"
  +++ |+#include <cstddef>
   35 |
```

This appears to be because classic SDL 1.2 has an `AC_CHECK_HEADERS` for `stddef.h` (the C equivalent of `<cstddef>`, with a definition of `offsetof`), but the substitute `SDL_config.h` in sdl12-compat doesn't define `HAVE_STDDEF_H`, resulting in `SDL_stdinc.h` not including `stddef.h`.

`stddef.h` is required by C89, and is unconditionally included by even very portable libraries like `libdbus`, so it should be safe to define `HAVE_STDDEF_H` and include `<stddef.h>` unconditionally on all platforms.

**Comment by smcv** [comment]
Reproducer:

```
#include "SDL.h"

struct a {
    int b;
};

int main(void)
{
  return offsetof(struct a, b);
}
```

`gcc -ot t.c `pkg-config --cflags --libs sdl` with sdl12-compat 1.2.64 ⇒ fails

`gcc -ot t.c -Iinclude/SDL` with the pull request that I'm about to open ⇒ succeeds
